[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hydrotwin"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.9"

# Apenas as dependências diretas que o código usa para rodar
dependencies = [
    "pandas",
    "pyserial",
    "streamlit",
    "requests",
    "python-dotenv",
    "uvicorn",
]

# Ferramentas usadas apenas para testes ou desenvolvimento
[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find] 
where = ["src"]